### ISSUE TITLE
Generator

### ISSUE THREAD

**Issue by D-Maxwell** [peotr26/new_super_bolcheland#11]
I would not refuse any potential incoming help whether it is in regards to the conceptualisation or the realisation of such a feature.

**Comment by JeanChipo** [comment]
Wouldn't it be easier, if not faster to put random data in the database ?
Even if there isn't a lot of data provided, it should be enough to progress in other tasks.

**Comment by peotr26** [comment]
I'm going to close this issue because it's out of date.
